name: HobbySpark
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        
    steps:
      - uses: actions/checkout@v4
      - name: Adding python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Installing packages
        run: | 
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Determine Version
        id: version
        shell: pwsh
        run: |
            $v = "${{ github.ref_name }}"
            $v = $v.TrimStart("v")
            "version=$v" >> $env:GITHUB_OUTPUT

      - name: Compile excecutable
        run: pyinstaller tks.spec

      - name: Verify executable exists
        shell: bash
        run: |
          if [ ! -f "dist/HobbySpark/HobbySpark" ]; then
            echo "ERROR:"
            echo "PyInstaller failed"
            exit 1
          fi
      - name: Install InnoSetup
        shell: powershell
        run: choco install innosetup -y

      - name: Locate ISCC
        id: iscc
        shell: powershell
        run: |
          $paths = @(
            "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
            "${env:ProgramFiles}\Inno Setup 6\ISCC.exe"
          )

          foreach ($path in $paths) {
            if (Test-Path $path) {
              "path=$path" >> $env:GITHUB_OUTPUT
              exit 0
            }
          }

          throw "Unable to locate ISCC.exe"
      - name: Verify installer files
        run: |
          if not exist installers\icon.ico (
              echo Missing icon.ico
              exit /b 1
          )

          if not exist installers\HobbySpark.iss (
              echo Missing HobbySpark.iss
              exit /b 1
          )
      - name: Build
        run: |
          "${{ steps.iscc.outputs.path}}" ^
          installers\HobbySpark.iss ^
          /DAppVersion=${{ steps.version.outputs.version }}

      - name: Verify executable exists
        shell: bash
        run: |
          if [ ! -f "dist/HobbySpark/HobbySpark" ]; then
            echo "ERROR:"
            echo "PyInstaller failed"
            exit 1
          fi

      - name: Create portable ZIP
        shell: powershell
        run: |
          Compress-Archive `
            -Path dist/HobbySpark/* `
            -DestinationPath `
            HobbySpark-${{ steps.version.outputs.version }}-Windows-Portable.zip

      - name: Rename installer
        shell: powershell
        run: |
          Move-Item `
            installers/Output/HobbySparkSetup.exe `
            HobbySpark-${{ steps.version.outputs.version }}-WindowsSetup.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: |
            HobbySpark-${{ steps.version.outputs.version }}-WindowsSetup.exe
            HobbySpark-${{ steps.version.outputs.version }}-Windows-Portable.zip
            
  ubuntu-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - name: Adding python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Installing packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Determine Version
        id: version
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            VERSION="0.0.${GITHUB_RUN_NUMBER}"
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUT" 

      - name: Compile excecutable
        run: pyinstaller tks.spec

      - name: Verify executable exists
        shell: bash
        run: |
          if [ ! -f "dist/HobbySpark/HobbySpark" ]; then
            echo "ERROR:"
            echo "PyInstaller failed"
            exit 1
          fi

      - name: Build Debian package
        shell: bash
        run: |
          chmod +x deb.sh
          ./deb.sh "${{ steps.version.outputs.version }}"

      - name: Compress
        run: tar -czf HobbySpark-${{steps.version.outputs.version}}-Linux-Portable.tar.gz dist/HobbySpark

      - name: Verify Debian package
        shell: bash
        run: |
          if [ ! -f HobbySpark-${{ steps.version.outputs.version }}-Linux-amd64-Installer.deb ]; then
            echo "Debian package was not generated."
            exit 1
          fi
      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: |
              HobbySpark-${{ steps.version.outputs.version }}-Linux-amd64-Installer.deb
              HobbySpark-${{ steps.version.outputs.version }}-Linux-Portable.tar.gz
  macOS-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Adding python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Installing packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Determine Version
        id: version
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            VERSION="0.0.${GITHUB_RUN_NUMBER}"
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUT" 
      - name: Compile excecutable
        run: pyinstaller tks.spec
      - name: Debug output
        run: |
          pwd
          find dist
      - name: Verify executable exists
        shell: bash
        run: |
          if [ ! -d "dist/HobbySpark.app" ]; then
              echo "ERROR:"
              echo "PyInstaller failed"
              exit 1
          fi
          mv dist/HobbySpark.app dist/HobbySpark-${{ steps.version.outputs.version }}-macOS-portable.app
      - name: Make the installer
        run: |
          pkgbuild \
            --install-location /Applications \
            --component dist/HobbySpark-${{ steps.version.outputs.version }}-macOS-portable.app \
            --identifier com.hobbyspark.app \
            --version "${{steps.version.outputs.version}}"\
            HobbySpark-${{steps.version.outputs.version}}-MacOS-Installer.pkg
      
      - name: Verify PKG exists
        run: |
          if [ ! -f "HobbySpark-${{ steps.version.outputs.version }}-MacOS-Installer.pkg" ]; then
            echo "PKG was not generated."
            exit 1
          fi 
      - name: Create portable macOS ZIP
        run: |
          ditto -c -k --sequesterRsrc --keepParent \
            "dist/HobbySpark-${{ steps.version.outputs.version }}-macOS-portable.app" \
            "HobbySpark-${{ steps.version.outputs.version }}-MacOS-Portable.zip"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MacOS
          path: |
            HobbySpark-${{ steps.version.outputs.version }}-MacOS-Installer.pkg
            HobbySpark-${{ steps.version.outputs.version }}-MacOS-Portable.zip
          

  release:
    needs:
      - build
      - macOS-build
      - ubuntu-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Show files
        run: find .

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{github.ref_name}}
          files: |
            Windows/*
            Linux/*
            MacOS/*
      
      
        
    
        
        
      
        
